#!/usr/bin/env python3
"""
Stage 4 — Generate agent.md per researcher.

agent.md is the RUNTIME system_prompt fragment used by orchestrator.
It's lighter and more templated than soul.md: condenses soul.md +
research_index.json anchors into a tight behavioral contract.

This calls gpt-5.5 once per researcher with:
  - soul.md (just-generated by Stage 2)
  - research_index.json anchors (paper_ids the agent will cite)
  - agent_template.md (skeleton)

Output: researchers/<slug>/agent.md

Usage:
    python3 generate_agent.py            # all
    python3 generate_agent.py zhi_jin    # one
    python3 generate_agent.py --force ...  # overwrite
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import httpx

sys.path.insert(0, str(Path(__file__).parent))
from load_researchers import list_researchers

ROOT = Path(__file__).parent
RESEARCHERS_ROOT = ROOT / "researchers"
ENV_FILE = Path("/data/projs/anetchat/.env")
TEMPLATE_FILE = ROOT / "agent_template.md"

HTTP_TIMEOUT = 120.0


def load_env() -> dict[str, str]:
    env = {}
    if not ENV_FILE.exists():
        return env
    for line in ENV_FILE.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, v = line.split("=", 1)
        env[k.strip()] = v.strip().strip('"').strip("'")
    return env


SYSTEM = """You compress a researcher's soul.md into a runtime agent.md
system-prompt fragment. The agent.md will be injected into a multi-agent
whiteboard chat (anet.chat), where this persona collaborates with 2-3
other researcher personas via short sticky-notes.

HARD RULES:
1. Keep agent.md UNDER 2500 chars total (tight runtime budget).
2. Every behavioral directive must be IMPERATIVE ("you do X") not
   descriptive ("he tends to ...").
3. Cite paper_ids verbatim from the provided list — these are the
   anchors the persona is allowed to "旁征博引" on the whiteboard.
4. Match the template's section structure exactly.
5. Output ONE markdown file, no preamble, starting with `# YOU ARE `."""

USER_TEMPLATE = """## TASK
Write agent.md for researcher: {slug}

## SOUL (full distillation, source-of-truth for traits)
<SOUL>
{soul}
</SOUL>

## CITATION ANCHORS (paper_ids agent may cite + key_insight refresher)
<ANCHORS>
{anchors_block}
</ANCHORS>

## TEMPLATE (mandatory structure)
<TEMPLATE>
{template}
</TEMPLATE>

## OUTPUT
Emit complete agent.md for `{slug}`. Start with `# YOU ARE `. ≤ 2500 chars."""


def build_anchors_block(slug: str, max_anchors: int = 15) -> str:
    """Compose the anchors section from research_index.json. If soul.md
    §7 already populated `anchors`, use those; else fall back to top-N
    by signal score (which build_index doesn't compute, so we just take
    first N from by_id with the richest key_insight)."""
    idx_path = RESEARCHERS_ROOT / slug / "research_index.json"
    if not idx_path.exists():
        return "(no research_index yet)"
    idx = json.loads(idx_path.read_text(encoding="utf-8"))
    anchors = idx.get("anchors") or []
    if not anchors:
        # fallback: papers with the longest key_insight, capped
        cands = sorted(
            ((pid, info) for pid, info in idx["by_id"].items()
             if info.get("key_insight")),
            key=lambda kv: -(len(kv[1].get("key_insight") or "")),
        )[:max_anchors]
        anchors = [pid for pid, _ in cands]
    lines = []
    for pid in anchors[:max_anchors]:
        info = idx["by_id"].get(pid, {})
        line = f"- `{pid}` — [{info.get('year')}|{info.get('venue')}] {info.get('key_insight') or ''}"
        lines.append(line)
    return "\n".join(lines)


def call_openai_chat(base_url: str, api_key: str, model: str,
                     system: str, user: str) -> str:
    headers = {"Authorization": f"Bearer {api_key}",
               "Content-Type": "application/json"}
    body = {
        "model": model,
        "messages": [
            {"role": "system", "content": system},
            {"role": "user", "content": user},
        ],
        "temperature": 0.2,
    }
    with httpx.Client(timeout=HTTP_TIMEOUT) as client:
        r = client.post(f"{base_url.rstrip('/')}/v1/chat/completions",
                        headers=headers, json=body)
        r.raise_for_status()
        return r.json()["choices"][0]["message"]["content"]


def generate_for(slug: str, env: dict[str, str], force: bool) -> bool:
    soul_path  = RESEARCHERS_ROOT / slug / "soul.md"
    agent_path = RESEARCHERS_ROOT / slug / "agent.md"
    if agent_path.exists() and not force:
        print(f"[skip] {slug:20s}  agent.md exists")
        return False
    if not soul_path.exists():
        print(f"[err]  {slug:20s}  soul.md missing — run generate_soul.py first")
        return False

    soul = soul_path.read_text(encoding="utf-8")
    template = TEMPLATE_FILE.read_text(encoding="utf-8")
    anchors_block = build_anchors_block(slug)

    user = USER_TEMPLATE.format(slug=slug, soul=soul, anchors_block=anchors_block,
                                template=template)
    base_url = env.get("OPENAI_BASE_URL") or "https://api.openai.com"
    api_key  = env.get("OPENAI_API_KEY")
    model    = env.get("OPENAI_MODEL", "gpt-5.5")
    if not api_key:
        print(f"[err]  {slug:20s}  OPENAI_API_KEY missing")
        return False

    print(f"[run]  {slug:20s}  calling {model}...", flush=True)
    out = call_openai_chat(base_url, api_key, model, SYSTEM, user).strip()
    if out.startswith("```"):
        out = out.split("\n", 1)[1] if "\n" in out else out
        if out.endswith("```"):
            out = out.rsplit("```", 1)[0]
    agent_path.write_text(out + "\n", encoding="utf-8")
    print(f"[ok]   {slug:20s}  wrote {len(out)} chars")
    return True


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("slug", nargs="*", help="researcher slug(s); empty = all")
    ap.add_argument("--force", action="store_true")
    args = ap.parse_args()
    env = load_env()
    slugs = args.slug or list_researchers()
    for slug in slugs:
        try:
            generate_for(slug, env, args.force)
        except Exception as e:
            print(f"[fail] {slug:20s}  {type(e).__name__}: {e}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
